### ISSUE TITLE
Multithread Usage Bug

### ISSUE THREAD

**Issue by Austin-s-h** [BaselAbujamous/clust#12]
Hello!
Thanks for publishing this tool, I look forward to comparing it with the other clustering methods I have tried. I ran into two difficulties while using it.

First of all, when using more than 1 processor (ex. -np 8), I run into a piping error.
![image](https://user-images.githubusercontent.com/44502805/47572797-d36eff00-d909-11e8-98db-80602e0a7f80.png)
The pipeline hangs up at 80% completion of Seed clusters production for 5+ minutes (I killed it afterward).
![image](https://user-images.githubusercontent.com/44502805/47573070-69a32500-d90a-11e8-84bd-b74638ba4179.png)
However, running _clust_ on the exact same data with -np 1 fixes this issue. I am testing it on an Ubuntu 18.04 server, let me know if you would like me to do any further diagnostics. 

Additionally, I don't know if it is worth reporting as an actual bug, but when all of the data is contained within one file...
```
clust_input1	HH6 HH6_pGFP_2, HH6_pGFP_3
clust_input1	HH8	HH8_pGFP_3,HH8_pGFP_1
clust_input1	HH10	HH10_pGFP_A1, HH10_pGFP_3, HH10_pGFP_2
clust_input1	HH12	HH12_pGFP_A1, HH12_pGFP_2, HH12_pGFP_1
clust_input1	HH14	HH14_pGFP_A1, HH14_pGFP_3, HH14_pGFP_2
clust_input1	HH16	HH16_pGFP_1, HH16_pGFP_A12, HH16_pGFP_A1
```
specifying -d as anything but 1 results in an error. Would it be possible to make this detect at the replicate level instead of dataset? or is this parameter more meant for multi-dataset analysis.

Thanks,
Austin

**Comment by Austin-s-h** [comment]
Thanks for the quick reply Basel!
I am running this on a 16 core Xeon W-2145 with 64GB of DDR4. 
The memory usage was stable (and low) you can see that the processes were taking around 120Mb of RAM each, and that was constant once the program hung up at 80%. I had this problem with -np 8 and -np16 multiple times. I can try running updates and restarting to see if that fixes anything.

**Comment by BaselAbujamous** [comment]
Hi Austin

I thought about the issue of multithreading that you have reported. I am unsure what would have caused it. However, I don't expect big gain in time at a given large number of cores, especially that the dataset seems to be small (you said one core did it in under 2 minutes). Did you try -np 2 or -np 4? Or did you try it when submitting multiple datasets? Hanging up at 80% sounds like a problem in cross-thread talks in a small job.

Please don't use your time to do further experiments if you haven't already done them. I already appreciate your time in writing up this issue.

Thanks
Basel

**Comment by alexharkess** [comment]
Just a quick note that I experience the same issue with multithreading (any value that isn't -np 1), with a hang at 80% at the seed cluster stage. Changing to -np 1 fixes it.

**Comment by SchwarzEM** [comment]
I've just re-encountered this same bug -- namely, when trying to run clust with "-n 4" or "-n 8", it hangs forever at the "80%" stage of seed clusters production.

I experienced this on two different Linux systems: one was Linux Mint 18 Sarah (GNU/Linux 4.4.0-21-generic x86_64), the other Linux CentOS (3.10.0-693.21.1.el7.x86_64 #1 SMP).  In both cases, I was working with the "Python package version 1.10.0 (2018)" version of clust.

And in both cases, when I checked the issues page, found this bug report, and tried "-n 1" instead, the jobs completed easily in minutes!

This delayed my getting the results by half a day.  Not a huge deal -- but since this seems to be a recurring bug, and since it may delay other users of clust, could some kind of warning about it be made prominent?  Either on the main documentation page for clust, or the help-arguments message one gets with "clust" alone or "clust --help", or both?

**Comment by BaselAbujamous** [comment]
Hi all,

Thanks a lot for reporting this bug repetitively. As Clust has become a lot faster since its first release, and as running Clust on multiple threads seems to cause this problem which I am not so clear on its reason, I have gone with @SchwarzEM 's suggestion to force -np 1 for now. In fact I have forced the -np option to be 1 now in version 1.10.7. A warning will appear if it was set otherwise.

Thanks again
Basel
