### ISSUE TITLE
plot issue

### ISSUE THREAD

**Issue by kianaknight** [BaselAbujamous/clust#35]
Hi
My  clusters_profiles.pdf , all clusters are black.
I need some help.
thanks a lot

**Comment by BaselAbujamous** [comment]
Hi. What do you mean by them being black? Can you please post a snapshot?

Hopefully I will be able to help :)

All the best
Basel

**Comment by kianaknight** [comment]
Hi，in your airticle
![image](https://user-images.githubusercontent.com/34878267/54067198-4b661200-4278-11e9-8f5a-cd91cea07d93.png)
while,my result is
![image](https://user-images.githubusercontent.com/34878267/54067318-7ef56c00-4279-11e9-85ef-1db4537680a7.png)
should i need further steps to have colors
thanks a lot

**Comment by BaselAbujamous** [comment]
The clust software produces clusters with these black lines, and in recent versions, as you can see, some shading is applied so you can visualise the density of the lines from the density of the black colour. I think this is more useful than the coloured version (which might on the other hand look nicer). As clust provides you with files including processed datasets and the contents of the clusters, you can redraw your clusters in any other way that you like using any other tool.

It is likely that future versions of clust will include options of how to visualise clusters in different ways (e.g. heatmaps), but not in the current version.

If you would like me to help drawing your clusters in a specific way as a one off thing, I am happy to so.

**Comment by kianaknight** [comment]
Okay，thanks a lot ！

**Comment by BaselAbujamous** [comment]
So I will close this issue, and please feel free to reopen it if needed or to come back with any other issues :)

All the best
Basel

**Comment by MafGal** [comment]
Hello @BaselAbujamous 
Thank you for making cluster available, really nice!

I see your reply to this issue, but could you give me a hand on this?
I would like my clusters to be lie the attached screenshot, the lines from inidivual genes in grey and the average in black.
Can you tell me which script and what I need to change in order to set it that way?

Many thanks in advance!

![ExCluster](https://user-images.githubusercontent.com/25986438/132926109-0213ee04-32f0-4b03-ac68-10cafe52ebab.png)
