### ISSUE TITLE
ValueError: invalid literal for float()

### ISSUE THREAD

**Issue by pixie-bioinfo** [BaselAbujamous/clust#6]
Hello,

I am trying to run the program using
`$ clust path_to_directory`

its giving these errors:

Traceback (most recent call last):
  File "/usr/local/bin/clust", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/clust/__main__.py", line 88, in main
    args.np, args.optimisation, args.q3s, args.deterministic)
  File "/usr/local/lib/python2.7/dist-packages/clust/clustpipeline.py", line 73, in clustpipeline
    returnSkipped=True)
  File "/usr/local/lib/python2.7/dist-packages/clust/scripts/io.py", line 28, in readDatasetsFromDirectory
    datafilesread = readDataFromFiles(datafileswithpath, delimiter, float, skiprows, skipcolumns, returnSkipped)
  File "/usr/local/lib/python2.7/dist-packages/clust/scripts/io.py", line 154, in readDataFromFiles
    usecols=range(skipcolumns, ncols), ndmin=2, comments=comm)
  File "/usr/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 848, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
ValueError: invalid literal for float(): 1,7.591893546,7.255723111,6.52040516,6.614578794,7.818629699,7.503905326,6.817377628,6.302704563,6.106799149,7.484905097,7.426335129,6.274657542,6.087165531,6.139690166,7.630860516,7.692840101,7.22647

Kindly help!

**Comment by BaselAbujamous** [comment]
Hi

VERSION UPDATED (v.1.6.0)!

I believe that the problem is that your data is comma delimited (commas separate between values in the line). _Clust_ assumes they are TAB delimited. I have updated _clust_ to accept files with any mixture of these delimiters:

TAB, space, comma, semicolon

The new version (1.6.0) should work on your data as it is. Otherwise, the older version (1.5.0) should work if you replace all commas in your data with TABs. "Pip install" will automatically install the newest version (if it does not, it would be fetching the older version from the cache, so try the --no-cache-dir option with the pip install command to force it to get the newest version).

Please let me know if the new version solves your problem.

Good luck.
Base

**Comment by pixie-bioinfo** [comment]
Thanks, its working fine now .
